apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addressbook-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: addressbook-deployment
    spec:
      containers:
      - name: addressbook
        #image: abhijitdey94/test_tomcat:13
        image: jenkins
        ports:
        - containerPort: 80

