apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-05-15T16:19:00Z
  labels:
    app: front-end
  name: front-end-lb
  namespace: default
  resourceVersion: "45872"
  selfLink: /api/v1/namespaces/default/services/front-end
  uid: 26023082-772d-11e9-8bde-42010aa000dd
spec:
  #clusterIP: 10.55.241.58
  #externalTrafficPolicy: Cluster
  ports:
  - name: 89-8888
    nodePort: 31524
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: front-end
  sessionAffinity: None
  type: LoadBalancer
