apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
  labels:
    service: addressbook-service
spec:
  selector:
    app: addressbook-deployment
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31444
    protocol: TCP
