apiVersion: v1
kind: Service
metadata:
  name: my-service2
  labels:
    service: my-service
spec:
  selector:
    app: test-deployment
  type: NodePort
  ports:
  - port: 80
    nodePort: 32222
    protocol: TCP
